[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf          ; <--- ВОТ ЭТО САМОЕ ГЛАВНОЕ!
monitor_speed = 115200

; Настройки памяти для твоей S3-N16R8
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB